name: IronElevators
main: me.ScarleTomato.IronElevators.IronElevators
version: gbl 1.10 [mc1.10]
description: >
             Easy Iron Block Elevators
permissions:
ironelevators.use:
  default: true
  description: Allow a player to teleport between elevators